site_name: open-mastr
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      docstring_style: numpy
  - include-markdown
  

watch:
  - open_mastr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - open-mastr: index.md
  - Getting Started: getting_started.md
  - The dataset: dataset.md
  - Development: 
    - Contributing: development/contributing_mirror.md
    - Release Procedure: development/release_procedure_mirror.md
    - Changelog: development/changelog_mirror.md
  - API Reference: reference.md

repo_url: https://github.com/OpenEnergyPlatform/open-MaStR
site_description: A package that provides an interface for downloading and processing the data of the Marktstammdatenregister (MaStR)
site_dir: _build


copyright: |
  &copy; 2023 <a href="https://reiner-lemoine-institut.de/"  target="_blank" rel="noopener">RLI</a> and <a href="https://fortiss.org"  target="_blank" rel="noopener">fortiss GmbH</a>
